---
name: Práctica Guardas y Pattern Matching
locale: es
type: practice
beta: false
teacher_info: ''
language: haskell
id_format: "%05d"
order:
- 401
- 402
- 403
- 404
- 405
- 406
- 407
private: false
